-- Quest FPV Ground Station — kahepoolne vestlus tracker'i ülesannete kohta
-- Käivita see üks kord Supabase Dashboard > SQL Editor's.

create table if not exists task_comments (
  id bigint generated by default as identity primary key,
  project_slug text not null,
  task_id text not null,
  author text not null default 'user' check (author in ('user','claude')),
  body text not null,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists task_comments_lookup
  on task_comments (project_slug, task_id, created_at);

alter table task_comments enable row level security;

-- Anon key (nii tracker veebis kui Claude curl kaudu) tohib lugeda ja kirjutada.
-- Sama usaldusmudel mis task_states tabelil juba on (privaatne tööriist, anon key pole avalik jagatud).
create policy "anon select task_comments" on task_comments
  for select using (true);

create policy "anon insert task_comments" on task_comments
  for insert with check (true);

create policy "anon update task_comments" on task_comments
  for update using (true);
